import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 16,
    backgroundColor: 'transparent',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(150, 150, 150, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  statusBadge: {
    position: 'absolute',
    bottom: -5,
    alignSelf: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(150, 150, 150, 0.2)',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#10B981',
  },
  name: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'center',
  },
  specialty: {
    fontSize: 18,
    color: '#2563EB',
    fontWeight: '600',
    marginBottom: 4,
  },
  tjm: {
    fontSize: 14,
    color: '#9BA1A6',
    marginBottom: 24,
  },
  actionContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginBottom: 32,
  },
  actionButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  callButton: {
    backgroundColor: 'rgba(150, 150, 150, 0.1)',
  },
  messageButton: {
    backgroundColor: 'rgba(150, 150, 150, 0.1)',
  },
  mailButton: {
    backgroundColor: 'rgba(150, 150, 150, 0.1)',
  },
  card: {
    backgroundColor: 'rgba(150, 150, 150, 0.05)',
    borderRadius: 24,
    marginHorizontal: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(150, 150, 150, 0.1)',
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#9BA1A6',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  infoText: {
    fontSize: 16,
    fontWeight: '500',
    flex: 1,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
  },
  customPickerButton: {
    backgroundColor: 'rgba(150, 150, 150, 0.1)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(150, 150, 150, 0.2)',
  },
  statusInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    marginRight: 10,
    fontSize: 16,
  },
  pickerText: {
    fontSize: 16,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'rgba(30, 41, 59, 1)',
    borderRadius: 24,
    width: '100%',
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 20,
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
  },
  modalCloseButton: {
    marginTop: 20,
    alignItems: 'center',
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
  },
  modalCloseText: {
    color: '#9BA1A6',
    fontWeight: '600',
  },
  materialModal: {
    backgroundColor: '#1E293B',
    borderRadius: 28,
    width: '90%',
    padding: 24,
    elevation: 24,
  },
  materialTitle: {
    fontSize: 24,
    fontWeight: '400',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  materialMessage: {
    fontSize: 14,
    color: '#9BA1A6',
    lineHeight: 20,
    marginBottom: 24,
  },
  materialInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#2563EB',
    color: '#FFFFFF',
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 0,
    marginBottom: 24,
  },
  materialActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  materialAction: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  materialActionText: {
    color: '#2563EB',
    fontWeight: '600',
    fontSize: 14,
    textTransform: 'uppercase',
  },
  highlight: {
    color: '#2563EB',
    fontWeight: '700',
  },
  taskInputContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: 'rgba(37, 99, 235, 0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.1)',
  },
  taskLabelHighlight: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563EB',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  taskInput: {
    fontSize: 16,
    color: 'inherit',
    fontWeight: '500',
    padding: 0,
    minHeight: 40,
    textAlignVertical: 'top',
  },
});
